baseURL = "https://tses89214.github.io/"
languageCode = "zh-tw"
title = "ChiaXuan 的個人網站"
theme = "hugo-PaperMod"

[params]
  # PaperMod 主題參數，可以稍後依喜好調整
  disableShare = false
  disableFancyHeader = false
  disableQuickSearch = false
  defaultContentLanguage = "zh"
  mainSections = ["blog", "portfolio"]
  dateFormat = "2006-01-02"
  author = "ChiaXuan"
  showReadingTime = true

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Portfolio"
    url = "/categories/portfolio/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/categories/blog/"
    weight = 3
