baseURL: https://tses89214.github.io/
languageCode: zh-tw
title: ChiaXuan 的個人網站
theme: hugo-PaperMod
params:
  disableShare: false
  disableFancyHeader: false
  disableQuickSearch: false
  defaultContentLanguage: zh
  mainSections:
    - blog
    - portfolio
  dateFormat: 2006-01-02
  author: ChiaXuan
  showReadingTime: true
  ShowBreadCrumbs: true
  ignoreLogs: true
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Portfolio
      url: /categories/portfolio/
      weight: 2
    - name: Blog
      url: /categories/blog/
      weight: 3


